name: 'Deploy to Firebase Cloud Functions Node v18'
author: 'muraterzioglu <hello@murat.codes>'
description: 'A GitHub Action to deploy to Firebase Cloud Functions with custom path and yarn support.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'black'
